### ISSUE TITLE
Can't even build it :(

### ISSUE THREAD

**Issue by punkjj** [Jonatino/Xena#2]
It gives out errors like "too many arguements for public! or something" for line 57,58 in xena.kt

**Comment by Jonatino** [comment]
@punkjj can you please download the project again, the build is now passing.

**Comment by punkjj** [comment]
@Jonatino Now I'm getting a error "variable "mousepointerGlow" is never used , xena.kt like 175"

**Comment by Jonatino** [comment]
@punkjj that's just a warning. You can ignore that.
