### ISSUE TITLE
cheat not working

### ISSUE THREAD

**Issue by cunyilmaz** [Jonatino/Xena#24]
Hello,

Xena Plugins are not working after latest CSGO update. (jdk 8)
I installed jdk 11 it still does not work.
![ss](https://user-images.githubusercontent.com/40922868/50020587-775e5800-ffe7-11e8-981e-3c746533f3ef.png)

pls help
Emre

**Comment by Jonatino** [comment]
@cunyilmaz make sure you're in game before running the cheat

**Comment by cunyilmaz** [comment]
Thank you so much :)
