### ISSUE TITLE
Not works after new update

### ISSUE THREAD

**Issue by izzy777** [Jonatino/Xena#35]
> Exception in thread "main" java.lang.IllegalStateException: Can not find offset inside of client_panorama.dll with pattern [-95, 0, 0, 0, 0, -123, -64, 15, -124, 0, 0, 0, 0, -128, -72, 0, 0, 0, 0, 0, 15, -124, 0, 0, 0, 0, 15, 16, 5]
>         at org.xena.offsets.misc.PatternScanner.byPattern(PatternScanner.java:55)
>         at org.xena.offsets.misc.PatternScanner.byPattern(PatternScanner.java:38)
>         at org.xena.offsets.offsets.ClientOffsets.load(ClientOffsets.kt:65)
>         at org.xena.offsets.OffsetManager.loadOffsets(OffsetManager.java:82)
>         at org.xena.offsets.OffsetManager.initAll(OffsetManager.java:68)
>         at org.xena.Main.main(Main.java:32)

**Comment by Linerzz** [comment]
Yep getting the same stuff

**Comment by izzy777** [comment]
@Linerzz , played like it is ))
