### ISSUE TITLE
It locks on any target

### ISSUE THREAD

**Issue by punkjj** [Jonatino/Xena#4]
it looks onto any target for ex- if someones is standing in my front i press CTRL , it will shoot someone else thru walls and the other guy kills me , MAKE IT LOCK ON THE NEAREST TARGET

**Comment by punkjj** [comment]
@Jonatino

**Comment by SkoshRG** [comment]
@punkjj Why don't you do that yourself? @Jonatino has already made a huge contribution by open sourcing his project, the least you can do is show some respect...

**Comment by Jonatino** [comment]
@SkoshRG I will be taking a look at this today. Waiting for my latest offsets to upload to maven though >.>

**Comment by Jonatino** [comment]
d666f68
