### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by mariodaelizabeth** [Jonatino/Xena#5]
Dear, Jonatino
Hello, i am a newcomer for your stuffs especially Xena.
I can't find how to build Xena. And, what should i do for dependencies such as offsets-scanner, JNA and JNM. Should i download it too ?
Thank you very much for your time.

Warm regards,

*

**Comment by Jonatino** [comment]
@mariodaelizabeth just run "run.bat"

**Comment by mariodaelizabeth** [comment]
@Jonatino Hello, Jonatino
Thank you very much for your time.
It works fine for me and no errors.
I saw in the menu such as 0: GlowESPPlugin, 1:ForceAimPlugin, 2: NoFlashPlugin, 3:AimAssistPlugin. How to enable Skin Changer and also Spin Bot plugin ?
Thank You

**Comment by Jonatino** [comment]
@mariodaelizabeth I recommend keeping those off for now because there are a few problems with them (caused game crash).

**Comment by mariodaelizabeth** [comment]
@Jonatino Thanks, mate
I will contact you, if i find any problems.
Thanks for the cool stuffs ;)

**Comment by Jonatino** [comment]
@mariodaelizabeth no problem. Enjoy =)
