### ISSUE TITLE
IS detected and other Questopn

### ISSUE THREAD

**Issue by Jerem584** [Jonatino/Xena#9]
Can i make my private on ? external / internal ? free right ? can i contribuate ? thanks; have a great day, and a great elove story

**Comment by Jonatino** [comment]
No its not detected, its external, sure you can contribute. No idea what you meant by "Can i make my private on ?"

**Comment by Jerem584** [comment]
Can i create my prviate cheat based on these source

**Comment by Jonatino** [comment]
Sure

**Comment by Jerem584** [comment]
Thanks, lets work ;) You are a great man.

**Comment by Jonatino** [comment]
Please star the project if you enjoy the cheat :)
